//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.ALBUMs = new HashSet<ALBUM>();
        }
    
        public string IDUSER { get; set; }
        public string PASSWORD { get; set; }
        public string NAME { get; set; }
        public string MAIL { get; set; }
        public string USERGROUP { get; set; }
    
        public virtual ICollection<ALBUM> ALBUMs { get; set; }
    }
}
